apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fvp6ca8j9-python
  janus-idp.io/tekton: fvp6ca8j9-python
  backstage.io/kubernetes-id: fvp6ca8j9-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fvp6ca8j9-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
